import type { NextPage } from 'next';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import dynamic from 'next/dynamic';

const DynamicComponent = dynamic(() => import('./components/vconsole'), {
  ssr: false,
});

const Home: NextPage = () => {

  const [value, setValue] = useState('')

  const handleClick = () => {
    if (value) {
      document.cookie = `proxy_subdomain=${value?.split(' ').join('')}`;
      window?.location?.reload();
    }
  };

  function getCookie(cname: string) {
    let name = cname + '=';
    let decodedCookie = decodeURIComponent(document.cookie);
    let ca = decodedCookie.split(';');
    for (let i = 0; i < ca.length; i++) {
      let c = ca[i];
      while (c.charAt(0) == ' ') {
        c = c.substring(1);
      }
      if (c.indexOf(name) == 0) {
        return c.substring(name.length, c.length);
      }
    }
    return '';
  }

  useEffect(() => {
    setValue(getCookie('proxy_subdomain'))
  }, [])

  return (
    <div className={styles.container}>
      <DynamicComponent />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>Next.js!</a>
        </h1>
        <p></p>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <label>输入代理地址：</label>
          <input
            value={value}
            onChange={(e) => setValue(e.target.value)}
            style={{ width: '12rem', height: '2rem', borderRadius: '1%' }}
            type="text"
            placeholder="osUserName"
          />
        </div>
        <p></p>
        <button
          onClick={handleClick}
          style={{ width: '6rem', height: '2rem', borderRadius: '5%' }}
        >
          保存并刷新
        </button>
      </main>

      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
